### PR TITLE
feat: add torii index pending option

### PR DESCRIPTION
**Pull request by glihm**

### CODE REVIEW

**Comment by glihm** [comment]
I've one issue running in the CLI, but tests seems to pass.
Will check that.

```
glihm [slot] cargo run --bin slot d create glihm-pr42 torii  --index-pending --rpc https://api.cartridge.gg/rpc/starknet-sepolia --world 0x1234 --start-block 88888
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `target/debug/slot d create glihm-pr42 torii --index-pending --rpc 'https://api.cartridge.gg/rpc/starknet-sepolia' --world 0x1234 --start-block 88888`
Error: Cannot query field "indexPending" on type "ToriiConfig".
glihm [slot] 
```

**Comment by glihm** [comment]
Oh, maybe just related to the update to be pushed on the clusters I guess.

**Comment by glihm** [comment]
Depends on PR-1497 for internal deployment.

**Comment by glihm** [comment]
@tarrencev @broody once internal is merged this one will unlock ryo sepolia.

**Comment by broody** [comment]
> @tarrencev @broody once internal is merged this one will unlock ryo sepolia.

Cool, I'll add `v0.7.0-alpha.0` to supported slot versions. Users will have to explicitly set the version for now.

**Pull request merged**
